// Lista de países integrada en la app (no depende de APIs externas).
// `region` (continente, en español) sirve para agrupar en reportes.
// Nombres en español; `code` es ISO 3166-1 alpha-2.

export const COUNTRIES = [
  // ── América ──
  { code: 'MX', name: 'México', region: 'América', subregion: 'Norteamérica' },
  { code: 'US', name: 'Estados Unidos', region: 'América', subregion: 'Norteamérica' },
  { code: 'CA', name: 'Canadá', region: 'América', subregion: 'Norteamérica' },
  { code: 'GT', name: 'Guatemala', region: 'América', subregion: 'Centroamérica' },
  { code: 'BZ', name: 'Belice', region: 'América', subregion: 'Centroamérica' },
  { code: 'SV', name: 'El Salvador', region: 'América', subregion: 'Centroamérica' },
  { code: 'HN', name: 'Honduras', region: 'América', subregion: 'Centroamérica' },
  { code: 'NI', name: 'Nicaragua', region: 'América', subregion: 'Centroamérica' },
  { code: 'CR', name: 'Costa Rica', region: 'América', subregion: 'Centroamérica' },
  { code: 'PA', name: 'Panamá', region: 'América', subregion: 'Centroamérica' },
  { code: 'CU', name: 'Cuba', region: 'América', subregion: 'Caribe' },
  { code: 'DO', name: 'República Dominicana', region: 'América', subregion: 'Caribe' },
  { code: 'PR', name: 'Puerto Rico', region: 'América', subregion: 'Caribe' },
  { code: 'JM', name: 'Jamaica', region: 'América', subregion: 'Caribe' },
  { code: 'HT', name: 'Haití', region: 'América', subregion: 'Caribe' },
  { code: 'BS', name: 'Bahamas', region: 'América', subregion: 'Caribe' },
  { code: 'BB', name: 'Barbados', region: 'América', subregion: 'Caribe' },
  { code: 'TT', name: 'Trinidad y Tobago', region: 'América', subregion: 'Caribe' },
  { code: 'AW', name: 'Aruba', region: 'América', subregion: 'Caribe' },
  { code: 'CW', name: 'Curazao', region: 'América', subregion: 'Caribe' },
  { code: 'KY', name: 'Islas Caimán', region: 'América', subregion: 'Caribe' },
  { code: 'CO', name: 'Colombia', region: 'América', subregion: 'Sudamérica' },
  { code: 'VE', name: 'Venezuela', region: 'América', subregion: 'Sudamérica' },
  { code: 'EC', name: 'Ecuador', region: 'América', subregion: 'Sudamérica' },
  { code: 'PE', name: 'Perú', region: 'América', subregion: 'Sudamérica' },
  { code: 'BO', name: 'Bolivia', region: 'América', subregion: 'Sudamérica' },
  { code: 'BR', name: 'Brasil', region: 'América', subregion: 'Sudamérica' },
  { code: 'PY', name: 'Paraguay', region: 'América', subregion: 'Sudamérica' },
  { code: 'UY', name: 'Uruguay', region: 'América', subregion: 'Sudamérica' },
  { code: 'AR', name: 'Argentina', region: 'América', subregion: 'Sudamérica' },
  { code: 'CL', name: 'Chile', region: 'América', subregion: 'Sudamérica' },
  { code: 'GY', name: 'Guyana', region: 'América', subregion: 'Sudamérica' },
  { code: 'SR', name: 'Surinam', region: 'América', subregion: 'Sudamérica' },

  // ── Europa ──
  { code: 'ES', name: 'España', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'PT', name: 'Portugal', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'FR', name: 'Francia', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'IT', name: 'Italia', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'GB', name: 'Reino Unido', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'IE', name: 'Irlanda', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'DE', name: 'Alemania', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'NL', name: 'Países Bajos', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'BE', name: 'Bélgica', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'LU', name: 'Luxemburgo', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'CH', name: 'Suiza', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'AT', name: 'Austria', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'MC', name: 'Mónaco', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'VA', name: 'Ciudad del Vaticano', region: 'Europa', subregion: 'Europa Occidental' },
  { code: 'GR', name: 'Grecia', region: 'Europa', subregion: 'Europa del Sur' },
  { code: 'HR', name: 'Croacia', region: 'Europa', subregion: 'Europa del Sur' },
  { code: 'SI', name: 'Eslovenia', region: 'Europa', subregion: 'Europa del Sur' },
  { code: 'MT', name: 'Malta', region: 'Europa', subregion: 'Europa del Sur' },
  { code: 'NO', name: 'Noruega', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'SE', name: 'Suecia', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'FI', name: 'Finlandia', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'DK', name: 'Dinamarca', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'IS', name: 'Islandia', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'EE', name: 'Estonia', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'LV', name: 'Letonia', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'LT', name: 'Lituania', region: 'Europa', subregion: 'Europa del Norte' },
  { code: 'PL', name: 'Polonia', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'CZ', name: 'República Checa', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'SK', name: 'Eslovaquia', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'HU', name: 'Hungría', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'RO', name: 'Rumania', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'BG', name: 'Bulgaria', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'UA', name: 'Ucrania', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'RU', name: 'Rusia', region: 'Europa', subregion: 'Europa del Este' },
  { code: 'RS', name: 'Serbia', region: 'Europa', subregion: 'Balcanes' },
  { code: 'BA', name: 'Bosnia y Herzegovina', region: 'Europa', subregion: 'Balcanes' },
  { code: 'ME', name: 'Montenegro', region: 'Europa', subregion: 'Balcanes' },
  { code: 'AL', name: 'Albania', region: 'Europa', subregion: 'Balcanes' },
  { code: 'MK', name: 'Macedonia del Norte', region: 'Europa', subregion: 'Balcanes' },
  { code: 'TR', name: 'Turquía', region: 'Europa', subregion: 'Eurasia' },

  // ── Asia ──
  { code: 'JP', name: 'Japón', region: 'Asia', subregion: 'Asia Oriental' },
  { code: 'CN', name: 'China', region: 'Asia', subregion: 'Asia Oriental' },
  { code: 'KR', name: 'Corea del Sur', region: 'Asia', subregion: 'Asia Oriental' },
  { code: 'TW', name: 'Taiwán', region: 'Asia', subregion: 'Asia Oriental' },
  { code: 'HK', name: 'Hong Kong', region: 'Asia', subregion: 'Asia Oriental' },
  { code: 'MO', name: 'Macao', region: 'Asia', subregion: 'Asia Oriental' },
  { code: 'MN', name: 'Mongolia', region: 'Asia', subregion: 'Asia Oriental' },
  { code: 'TH', name: 'Tailandia', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'VN', name: 'Vietnam', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'KH', name: 'Camboya', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'LA', name: 'Laos', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'MM', name: 'Birmania (Myanmar)', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'MY', name: 'Malasia', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'SG', name: 'Singapur', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'ID', name: 'Indonesia', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'PH', name: 'Filipinas', region: 'Asia', subregion: 'Sudeste Asiático' },
  { code: 'IN', name: 'India', region: 'Asia', subregion: 'Asia del Sur' },
  { code: 'NP', name: 'Nepal', region: 'Asia', subregion: 'Asia del Sur' },
  { code: 'LK', name: 'Sri Lanka', region: 'Asia', subregion: 'Asia del Sur' },
  { code: 'MV', name: 'Maldivas', region: 'Asia', subregion: 'Asia del Sur' },
  { code: 'BT', name: 'Bután', region: 'Asia', subregion: 'Asia del Sur' },
  { code: 'PK', name: 'Pakistán', region: 'Asia', subregion: 'Asia del Sur' },
  { code: 'BD', name: 'Bangladés', region: 'Asia', subregion: 'Asia del Sur' },
  { code: 'AE', name: 'Emiratos Árabes Unidos', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'QA', name: 'Catar', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'SA', name: 'Arabia Saudita', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'OM', name: 'Omán', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'BH', name: 'Baréin', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'KW', name: 'Kuwait', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'JO', name: 'Jordania', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'IL', name: 'Israel', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'LB', name: 'Líbano', region: 'Asia', subregion: 'Medio Oriente' },
  { code: 'GE', name: 'Georgia', region: 'Asia', subregion: 'Cáucaso' },
  { code: 'AM', name: 'Armenia', region: 'Asia', subregion: 'Cáucaso' },
  { code: 'AZ', name: 'Azerbaiyán', region: 'Asia', subregion: 'Cáucaso' },
  { code: 'KZ', name: 'Kazajistán', region: 'Asia', subregion: 'Asia Central' },
  { code: 'UZ', name: 'Uzbekistán', region: 'Asia', subregion: 'Asia Central' },

  // ── África ──
  { code: 'MA', name: 'Marruecos', region: 'África', subregion: 'Norte de África' },
  { code: 'EG', name: 'Egipto', region: 'África', subregion: 'Norte de África' },
  { code: 'TN', name: 'Túnez', region: 'África', subregion: 'Norte de África' },
  { code: 'DZ', name: 'Argelia', region: 'África', subregion: 'Norte de África' },
  { code: 'ZA', name: 'Sudáfrica', region: 'África', subregion: 'África Austral' },
  { code: 'NA', name: 'Namibia', region: 'África', subregion: 'África Austral' },
  { code: 'BW', name: 'Botsuana', region: 'África', subregion: 'África Austral' },
  { code: 'ZW', name: 'Zimbabue', region: 'África', subregion: 'África Austral' },
  { code: 'ZM', name: 'Zambia', region: 'África', subregion: 'África Austral' },
  { code: 'MZ', name: 'Mozambique', region: 'África', subregion: 'África Austral' },
  { code: 'KE', name: 'Kenia', region: 'África', subregion: 'África Oriental' },
  { code: 'TZ', name: 'Tanzania', region: 'África', subregion: 'África Oriental' },
  { code: 'UG', name: 'Uganda', region: 'África', subregion: 'África Oriental' },
  { code: 'RW', name: 'Ruanda', region: 'África', subregion: 'África Oriental' },
  { code: 'ET', name: 'Etiopía', region: 'África', subregion: 'África Oriental' },
  { code: 'MU', name: 'Mauricio', region: 'África', subregion: 'África Oriental' },
  { code: 'SC', name: 'Seychelles', region: 'África', subregion: 'África Oriental' },
  { code: 'MG', name: 'Madagascar', region: 'África', subregion: 'África Oriental' },
  { code: 'NG', name: 'Nigeria', region: 'África', subregion: 'África Occidental' },
  { code: 'GH', name: 'Ghana', region: 'África', subregion: 'África Occidental' },
  { code: 'SN', name: 'Senegal', region: 'África', subregion: 'África Occidental' },
  { code: 'CV', name: 'Cabo Verde', region: 'África', subregion: 'África Occidental' },

  // ── Oceanía ──
  { code: 'AU', name: 'Australia', region: 'Oceanía', subregion: 'Australasia' },
  { code: 'NZ', name: 'Nueva Zelanda', region: 'Oceanía', subregion: 'Australasia' },
  { code: 'FJ', name: 'Fiyi', region: 'Oceanía', subregion: 'Melanesia' },
  { code: 'PF', name: 'Polinesia Francesa (Tahití)', region: 'Oceanía', subregion: 'Polinesia' },
  { code: 'CK', name: 'Islas Cook', region: 'Oceanía', subregion: 'Polinesia' },
  { code: 'WS', name: 'Samoa', region: 'Oceanía', subregion: 'Polinesia' },
  { code: 'PG', name: 'Papúa Nueva Guinea', region: 'Oceanía', subregion: 'Melanesia' },
].sort((a, b) => a.name.localeCompare(b.name, 'es'));

export const COUNTRY_NAMES = COUNTRIES.map(c => c.name);

// Mapa nombre → continente, para agrupar destinos en reportes
export const COUNTRY_REGION = COUNTRIES.reduce((acc, c) => {
  acc[c.name] = c.region;
  return acc;
}, {});
